//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sift.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EditList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditList() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sift.Strings.EditList", typeof(EditList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Domain [Domain] has already been added..
        /// </summary>
        internal static string AlreadyAddedDomain {
            get {
                return ResourceManager.GetString("AlreadyAddedDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IP [IP] has already been added..
        /// </summary>
        internal static string AlreadyAddedIP {
            get {
                return ResourceManager.GetString("AlreadyAddedIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL [URL] has already been added..
        /// </summary>
        internal static string AlreadyAddedURL {
            get {
                return ResourceManager.GetString("AlreadyAddedURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Domain].
        /// </summary>
        internal static string DomainReplaceString {
            get {
                return ResourceManager.GetString("DomainReplaceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Domain [Domain]..
        /// </summary>
        internal static string InvalidDomain {
            get {
                return ResourceManager.GetString("InvalidDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid IP [IP]..
        /// </summary>
        internal static string InvalidIP {
            get {
                return ResourceManager.GetString("InvalidIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL [URL]..
        /// </summary>
        internal static string InvalidURL {
            get {
                return ResourceManager.GetString("InvalidURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [IP].
        /// </summary>
        internal static string IPReplaceString {
            get {
                return ResourceManager.GetString("IPReplaceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Domain List.
        /// </summary>
        internal static string ListEditDomainTitle {
            get {
                return ResourceManager.GetString("ListEditDomainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit IP List.
        /// </summary>
        internal static string ListEditIPTitle {
            get {
                return ResourceManager.GetString("ListEditIPTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit URL List.
        /// </summary>
        internal static string ListEditURLTitle {
            get {
                return ResourceManager.GetString("ListEditURLTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [URL].
        /// </summary>
        internal static string URLReplaceString {
            get {
                return ResourceManager.GetString("URLReplaceString", resourceCulture);
            }
        }
    }
}
