//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sift.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainForm() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sift.Strings.MainForm", typeof(MainForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        internal static string ListDeleteConfirmation {
            get {
                return ResourceManager.GetString("ListDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting the list group deletes all subgroups and their lists. Are you sure you want to delete the list?.
        /// </summary>
        internal static string ListDeleteWarning {
            get {
                return ResourceManager.GetString("ListDeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable List.
        /// </summary>
        internal static string ListDisable {
            get {
                return ResourceManager.GetString("ListDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable List.
        /// </summary>
        internal static string ListEnable {
            get {
                return ResourceManager.GetString("ListEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string ListGroupCustom {
            get {
                return ResourceManager.GetString("ListGroupCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        internal static string ListGroupDeleteConfirmation {
            get {
                return ResourceManager.GetString("ListGroupDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting a list removes the list file from your computer. Are you sure you want to delete the list?.
        /// </summary>
        internal static string ListGroupDeleteWarning {
            get {
                return ResourceManager.GetString("ListGroupDeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Group.
        /// </summary>
        internal static string ListGroupDisable {
            get {
                return ResourceManager.GetString("ListGroupDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Group.
        /// </summary>
        internal static string ListGroupEnable {
            get {
                return ResourceManager.GetString("ListGroupEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New List Group.
        /// </summary>
        internal static string ListGroupNew {
            get {
                return ResourceManager.GetString("ListGroupNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Add.
        /// </summary>
        internal static string ListGroupQuickAdd {
            get {
                return ResourceManager.GetString("ListGroupQuickAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New List.
        /// </summary>
        internal static string ListNew {
            get {
                return ResourceManager.GetString("ListNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        internal static string ListTypeDomain {
            get {
                return ResourceManager.GetString("ListTypeDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP.
        /// </summary>
        internal static string ListTypeIP {
            get {
                return ResourceManager.GetString("ListTypeIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string ListTypeURL {
            get {
                return ResourceManager.GetString("ListTypeURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to localhost.
        /// </summary>
        internal static string NetworkLocalhost {
            get {
                return ResourceManager.GetString("NetworkLocalhost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password entered does not match the password confirmation..
        /// </summary>
        internal static string PasswordMismatch {
            get {
                return ResourceManager.GetString("PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text you entered is not a valid URL, Domain or IP..
        /// </summary>
        internal static string QuickAddInvalid {
            get {
                return ResourceManager.GetString("QuickAddInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communications error. Check the host name and port settings and try again.
        /// </summary>
        internal static string RemotingConnectionFailure {
            get {
                return ResourceManager.GetString("RemotingConnectionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success..
        /// </summary>
        internal static string RemotingConnectionSuccess {
            get {
                return ResourceManager.GetString("RemotingConnectionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        internal static string ServiceDisableAction {
            get {
                return ResourceManager.GetString("ServiceDisableAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string ServiceDisabled {
            get {
                return ResourceManager.GetString("ServiceDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string ServiceEnableAction {
            get {
                return ResourceManager.GetString("ServiceEnableAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string ServiceEnabled {
            get {
                return ResourceManager.GetString("ServiceEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sift service was not found on the specified computer. Check your service name and remoting port setting..
        /// </summary>
        internal static string ServiceNotFound {
            get {
                return ResourceManager.GetString("ServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string ServiceStartAction {
            get {
                return ResourceManager.GetString("ServiceStartAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        internal static string ServiceStarted {
            get {
                return ResourceManager.GetString("ServiceStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sift service is running..
        /// </summary>
        internal static string ServiceStartedDescription {
            get {
                return ResourceManager.GetString("ServiceStartedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sift serivce is starting ....
        /// </summary>
        internal static string ServiceStartingDescription {
            get {
                return ResourceManager.GetString("ServiceStartingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string ServiceStatisticsUnknownCharacter {
            get {
                return ResourceManager.GetString("ServiceStatisticsUnknownCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string ServiceStopAction {
            get {
                return ResourceManager.GetString("ServiceStopAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        internal static string ServiceStopped {
            get {
                return ResourceManager.GetString("ServiceStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sift service is stopped..
        /// </summary>
        internal static string ServiceStoppedDescription {
            get {
                return ResourceManager.GetString("ServiceStoppedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sift serivce is stopping ....
        /// </summary>
        internal static string ServiceStoppingDescription {
            get {
                return ResourceManager.GetString("ServiceStoppingDescription", resourceCulture);
            }
        }
    }
}
